### ISSUE TITLE
Nominating RafaelGSS to the TSC

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/TSC#1308] opened 2022-11-16 23:17 UTC
I would like to nominate @RafaelGSS to the TSC. In addition to [code contributions to Node.js core](https://github.com/nodejs/node/commits?author=rafaelgss), Rafael has a record of collaboration across multiple teams and working groups including: Release WG (co-led the recent major release, security releases, and regular releases), Security WG, security release stewarding and triage, and many other groups and teams. He has also led discussions in the project such as [security best practices](https://github.com/nodejs/nodejs.org/pull/4896), [threat model](https://github.com/nodejs/node/pull/45223), and [experimental features](https://github.com/nodejs/TSC/issues/1299).

I think Rafael would be a great addition to the TSC and would offer valuable additional context from the many teams he is involved in.

There have been no objections from the private TSC discussion, and I have verified his interest.

**Comment by richardlau** [comment] 2022-11-16 23:25
+1 from me.

**Comment by jasnell** [comment] 2022-11-16 23:47
+1

**Comment by aduh95** [comment] 2022-11-17 00:12
+1

**Comment by cjihrig** [comment] 2022-11-17 00:30
+1

**Comment by gireeshpunathil** [comment] 2022-11-17 02:01
+1. (Also worth mentioning the contributions and initiatives in the Diagnostics WG.)

**Comment by ShogunPanda** [comment] 2022-11-17 08:31
Big +1! Totally deserved!

**Comment by mhdawson** [comment] 2022-11-17 13:54
+1 from me

**Comment by Trott** [comment] 2022-11-17 17:13
+1

**Comment by RaisinTen** [comment] 2022-11-21 06:27
Definitely +1!

**Comment by joyeecheung** [comment] 2022-11-22 21:16
+1

**Comment by apapirovski** [comment] 2022-11-23 15:03
+1

**Comment by aduh95** [comment] 2022-11-23 16:32
@nodejs/tsc Please comment +1 if you are in favor, -1 if you are against, or if you want to abstain please also say so. Several members have reacted with a 👍 which seems to indicate they are in favor but haven't commented, so please consider doing so :) (@BethGriggs don't forget that you being the one open the issue doesn't mean you can't vote on it, I would need an explicit +1 from you as well).
I suggest to keep it open for another 7 days to give time for everyone to vote, but if we get all the votes before that, that's for the better.

**Comment by targos** [comment] 2022-11-23 16:34
+1. I assumed 👍 would count as a vote

**Comment by richardlau** [comment] 2022-11-23 16:35
+1 as vote.

**Comment by legendecas** [comment] 2022-11-23 17:00
+1

**Comment by BethGriggs** [comment] 2022-11-23 17:24
+1. I assumed we'd count both 👍🏻  from TSC members original nomination as a vote as we have in the past (https://github.com/nodejs/TSC/issues/1282#issuecomment-1243829292).

**Comment by GeoffreyBooth** [comment] 2022-11-23 17:52
+1

**Comment by Trott** [comment] 2022-11-23 17:53
In the past, GitHub reactions were understood to count as votes. I can see a reason for changing that in that after enough reactions, it becomes hard to see everyone who reacted. (You can still get the full list from the API but that's not convenient.)

I do think, though, that it is abundantly safe to assume that the person who is nominating is voting "yes" and that is what we have always done in the past.

**Comment by aduh95** [comment] 2022-11-23 18:02
I can't find it again, but I remember that I some point someone pointed out that reactions are not a great tool for this kind of vote as they don't send notifications and it doesn't leave a trace if someone is changing their vote. (or maybe in the API, but comments are just way easier to check.)

> I do think, though, that it is abundantly safe to assume that the person who is nominating is voting "yes" and that is what we have always done in the past.

Yeah actually, that makes sense, for this kind of issue there's no reason for someone to open a nomination they don't support without saying in the OP they don't support it.

**Comment by BridgeAR** [comment] 2022-11-23 18:11
+1

**Comment by mhdawson** [comment] 2022-11-24 14:12
@aduh95 how about we give people 6 days from the time of your comment, I think that might let us close the vote before the next meeting on the 30th. Rafael will be invited for the OSSF discussion anyway but it would be nice to have him confirmed by then.

**Comment by mhdawson** [comment] 2022-11-29 22:34
I'll have to check to see if any addition TSC member voted from what is tallied in https://github.com/nodejs/TSC/issues/1308#issuecomment-1325348043 but there are no new objections so I think we can considered this complete.

I volunteered to onboard @RafaelGSS since @BethGriggs is out this week.  I'm going to start that tomorrow.

**Comment by fhinkel** [comment] 2022-11-30 14:31
+1

**Comment by mhdawson** [comment] 2022-11-30 15:18
Starting onboarding

-[ ]  Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md).
* Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
* Change the new member's role in the GitHub `nodejs` organization to `Owner`.
* Add them to the `@nodejs-private` org and with an `Owner` role.
* Add them to the `@nodejs-private/security-tsc` team.
* Add them to the `@pkgjs` org and with an `Owner` role.
* Add them to the `@pkgjs/node-tsc` team.
* Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
  Have them turn on two-factor authentication after they have joined.
* Add them to the `tsc` and `crypto-export` mailing lists.
* Add them to the [nodejs-tsc](https://groups.google.com/g/nodejs-tsc) Google Group as owners, so they receive Calendar invites for TSC meetings.
* Update the `@nodejs/node` repository README to reflect membership in the TSC.
* Update <https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/invited_tsc> to reflect membership in the TSC.

**Comment by mhdawson** [comment] 2022-11-30 16:00
@mcollina and @ronag were +1 in the thumbs up in original post, @danielleadams was in the hurray as  well and therefore believe was in the thumbs (which we can't tell) counting them as part of final votes. Let me know if that was not the right thing to do.

Based on that I have the final vote as :

Yes: 18 (@aduh95, @apapirovski, @BethGriggs, @BridgeAR, @cjihrig, @danielleadams, @fhinkel, @GeoffreyBooth, @gireeshpunathil, @jasnell, @joyeecheung, @legendecas, @mcollina, @mhdawson, @RaisinTen, @richardlau, @ronag, @targos, @Trott)
No: 0
Abstain: 0

**Comment by mhdawson** [comment] 2022-11-30 17:56
@aduh95 thanks, that was next on my list of PRs. With that done I'm going to close out this issue.

**Closed by mhdawson** 2022-11-30 17:56 UTC
Labels: tsc-agenda
