### ISSUE TITLE
V8 currency and Node.js 15

### ISSUE THREAD

**Issue by targos** [nodejs/TSC#931] opened 2020-09-24 10:49 UTC
This issue is mainly about https://github.com/nodejs/node/pull/34337

We are now one month after the stable upstream release of V8 8.5. Unfortunately, the PR is still not ready to be merged, and I'm afraid that we may not be able to fix it soon enough for the release of Node.js 15.0.0, which would still have the same V8 version as Node.js 14.

It is now mainly blocked on a cross-compilation issue with ARM on Linux and I do not know what to do anymore. I have no experience with cross-compilation myself. @gengjiawen has been very helpful so far with the other issues (especially on Windows, thanks a lot! 🙇 ) but also seems out of ideas.

We tried to ping the `platform-arm` team and nobody answered (it's a very small team).
I'm opening an issue here hoping it gets some visibility. We haven't been so late with V8 updates in a very long time.

**Comment by mcollina** [comment] 2020-09-24 11:33
I think we should ship without ARM on Linux if we do not have the capabilities to maintain it. Keeping V8 currency is a primary goal.

**Comment by targos** [comment] 2020-09-24 11:38
@mcollina It's current a tier 1 platform: 
![Uploading image.png…]()

**Comment by mcollina** [comment] 2020-09-24 11:42
Either we reach out to ARM themselves or do a public call for help and we receive some help, or we downgrade it as our volunteers for supporting that platform are not there anymore.

**Comment by devsnek** [comment] 2020-09-24 15:41
I fear we may lock out a large number of students if we drop Linux arm. I'd love to assist but my arm hardware is currently across the country from me due to some annoying circumstances.

**Comment by mcollina** [comment] 2020-09-24 15:45
> I fear we may lock out a large number of students if we drop Linux arm

I 100% agree, I'm just reporting the current state of things - I'm just measuring the current state of affairs: we lack volunteers for ARM.

---

@bnb maybe we can do a call to arms on twitter from the `@nodejs` account?

**Comment by bnb** [comment] 2020-09-24 16:18
@mcollina I would be happy to. What specifically do we want to say?

**Comment by targos** [comment] 2020-09-24 16:20
Note that probably no ARM hardware is needed to fix the build issue as it happens during cross-compilation on the host (x64).

**Comment by MylesBorins** [comment] 2020-09-24 18:20
I can maybe take a look. Have we pinged the V8 team at all? In the past I was able to get them to help with build issues

**Comment by mmarchini** [comment] 2020-09-24 18:29
I can try to help over the weekend

**Comment by mhdawson** [comment] 2020-09-24 19:56
I assume this would affect apple on arm as well ?  Just want to understand so that we know what people/companies we might reach out to in respect to finding more people to help out on the arm platform.

**Comment by mmarchini** [comment] 2020-09-24 21:13
Do we have instructions somewhere for cross-compilation? Couldn't find any on [BUILDING.md](https://github.com/nodejs/node/blob/master/BUILDING.md)

**Comment by targos** [comment] 2020-09-25 06:33
@mmarchini There are some hints here: https://github.com/nodejs/node/issues/35252

**Comment by mmarchini** [comment] 2020-09-25 20:20
Ok, I think I got it building. Thank you @targos! Will share a gist with steps to build once I confirm it works.

Will also try to use QEMU to test. If it works I might send a PR to add a test-linux-arm Action 🔥

**Comment by nschonni** [comment] 2020-09-25 20:23
@mmarchini you might want to take a look at https://github.com/nodejs/docker-node/pull/1334 where there is an approach for using QEMU with GitHub Actions

**Comment by mmarchini** [comment] 2020-09-25 20:28
Nice! Will definitely take a look.

**Comment by mmarchini** [comment] 2020-09-25 21:20
![image](https://user-images.githubusercontent.com/4048656/94316990-3f18d700-ff3a-11ea-9338-8f270bb5155a.png)

👀

(I might be derailing this issue, will open a tracking issue on nodejs/node)

**Comment by mmarchini** [comment] 2020-09-25 22:28
For anyone wanting to help:

https://github.com/mmarchini/node-arm-cross-builder

**Comment by gengjiawen** [comment] 2020-09-26 09:05
> For anyone wanting to help:
> 
> [mmarchini/node-arm-cross-builder](https://github.com/mmarchini/node-arm-cross-builder)

What's the minimal kernel ? 4.14 ?

![image](https://user-images.githubusercontent.com/3759816/94337088-5fb85e00-001a-11eb-937c-508bbed5e58f.png)

**Comment by mmarchini** [comment] 2020-09-26 09:12
No idea, I ran it on Ubuntu 20.04. I think in your case it's a mismatch between the docket image (Ubuntu 18.04) and the kernel versions (which is too old for Ubuntu 18.04).


Either way, as long as it builds I guess it's fine? The problem we're having is on build time

**Comment by mmarchini** [comment] 2020-09-26 09:15
In other words if you downgrade the docker image to 16.04 it should work

**Comment by gengjiawen** [comment] 2020-09-26 14:49
Docker image share kernel with host, should be the kernel being old. Anyway, I can test the build now :)

**Comment by mmarchini** [comment] 2020-09-26 22:49
Yes, docker container will share kernel with host, but it will install packages based on the distro image, which could lead to mismatch between kernel and expected kernel by a package. I think it's likely that qemu is built for a specific kernel version or with a minimum kernel greater than 4.4. By using a Ubuntu 16.04 image instead qemu (or whatever is expecting a higher kernel version) should work.

**Comment by sxa** [comment] 2020-09-29 11:28
> I assume this would affect apple on arm as well ? Just want to understand so that we know what people/companies we might reach out to in respect to finding more people to help out on the arm platform.

I assume this is specific to 32-bit arm and therefore would NOT affect aarch64?

**Comment by gengjiawen** [comment] 2020-09-29 15:47
The issue is fixed by me. And @targos start V8 8.6 for Node.js 15 in https://github.com/nodejs/node/pull/35415.

**Comment by gengjiawen** [comment] 2020-09-29 15:58
> The issue is fixed by me. And @targos start V8 8.6 for Node.js 15 in [nodejs/node#35415](https://github.com/nodejs/node/pull/35415).

And great thanks @rvagg and @mmarchini for the cross-compile env setup.

**Comment by mmarchini** [comment] 2020-09-29 16:02
I believe this issue can be closed? @targos

**Comment by targos** [comment] 2020-10-04 08:51
I'm reopening for visibility because we hit other issues with V8 8.6: https://github.com/nodejs/node/pull/35415

**Comment by targos** [comment] 2020-10-18 13:03
Just need one more TSC review on https://github.com/nodejs/node/pull/35415

**Closed** 2020-10-18 18:21 UTC
