### ISSUE TITLE
Closing issues too quickly before they can be discussed

### ISSUE THREAD

**Issue by jasnell** [nodejs/TSC#855] opened 2020-04-24 15:18 UTC
Sometimes, an issue is opened and it's obvious that it can be resolved quickly and without much discussion... Then, there are times like this: https://github.com/nodejs/node/issues/33034 ... where one collaborator closes an issue that is opened clearly for the purpose of revisiting a prior decision made by the TSC and the issue is closed nearly immediately by a single collaborator who does not want the decision to be revisited at all and we end up with a back and forth between collaborators about whether the issue should be opened or closed that just adds pointless noise.

I've been thinking for some time that it would likely be a good idea to have a policy on closing issues that is similar to our fast track policy. That is, issues should be left open for at least 24 hours by default. If a collaborator wishes an issue to be closed within that 24 hour window, they would post a comment requesting that it be closed that must be given a 👍 by at least two other collaborators. The 24 hour window should give enough other collaborators time to at least see the issue and determine if they would like to engage.

The obvious exceptions to this rule would be any issues subject to moderation, issues that are obvious support type questions, or invalid bug reports (or reports of issues already resolved). I'm sure we could come up with a few other reasonable exceptions, I just don't want to see the kind of back and forth we're seeing again in https://github.com/nodejs/node/issues/33034

**Comment by sam-github** [comment] 2020-04-24 17:11
I don't think this policy would help in the case mentioned.

The issue can be left open for 24 hours... while people debate whether it should be closed.

Or it can be left closed, ... while people debate whether it should be open.

Or closed, opened, then closed, then opened... while people debate whether it should be open or close.

In all variants, the problem is the tone of the debate, not the opening or closing.

There are going to be disagreements, what is important is that people state clearly why they disagree, variants of "I see no merit in what you say" are not constructive.

> I see zero discussion on this particular topic in that thread. 

- https://github.com/nodejs/node/issues/33034#issuecomment-619042697

It is absolutely OK for us to revisit issues discussed in the past, and behaviour that has existed for years. Its absolutely OK for people to work on whatever they think is important and worth their time, but that comment was not so informative, the clarification that came later (https://github.com/nodejs/node/issues/33034#issuecomment-619051778) works better.

Stuff happens, we all spend a lot of time commenting on github, its easy to be excessively brief and have to go back and elaborate, but lets not allow cumbersome process to overtake collegial and fullsome expression of opinions.

Many issues we used to close immediately we now deal with by transferring to "nodejs/help". GH notifications are a firehose, if we have to revisit every issue we look at and think "that's not an issue it should be closed" again 24 hours after we first saw it, managing issues is going to get even more time consuming. I don't think we should even consider that without a) being sure it solves a problem, and b)  tooling (for example, we could replace closing with a tag "close soon" and  let a bot do it for us after 24 hours).

But I still think this is an attempted process solution for a human interaction problem.

**Comment by jasnell** [comment] 2020-04-24 17:54
Definitely cannot argue with any of that. I guess the concern that I'm having is that this definitely is not the first time issues are closed so quickly and so dismissively without giving adequate opportunity for discussion and consensus building, and there seems to be no willingness to engage more constructively in those cases. It is... frustrating. I do like the idea of leveraging the bot to close issues rather than explicit close.

**Comment by mhdawson** [comment] 2020-10-08 17:16
@jasnell do you think this still need to be open? If so are there concrete next steps?

**Comment by mhdawson** [comment] 2020-11-23 22:14
Closing as there has not been a response for quite some time. @jasnell please re-open if you don't think that is the right thing to do.

**Closed by mhdawson** 2020-11-23 22:14 UTC
