### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2018-06-13

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#551] opened 2018-06-11 12:05 UTC
## Time

**UTC Wed 13-Jun-2018 22:00 (10:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 13-Jun-2018 15:00 (03:00 PM) |
| US / Mountain | Wed 13-Jun-2018 16:00 (04:00 PM) |
| US / Central  | Wed 13-Jun-2018 17:00 (05:00 PM) |
| US / Eastern  | Wed 13-Jun-2018 18:00 (06:00 PM) |
| London        | Wed 13-Jun-2018 23:00 (11:00 PM) |
| Amsterdam     | Thu 14-Jun-2018 00:00 (12:00 AM) |
| Moscow        | Thu 14-Jun-2018 01:00 (01:00 AM) |
| Chennai       | Thu 14-Jun-2018 03:30 (03:30 AM) |
| Hangzhou      | Thu 14-Jun-2018 06:00 (06:00 AM) |
| Tokyo         | Thu 14-Jun-2018 07:00 (07:00 AM) |
| Sydney        | Thu 14-Jun-2018 08:00 (08:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2018-06-13&iso=20180613T22
* or http://www.wolframalpha.com/input/?i=10PM+UTC%2C+Jun+13%2C+2018+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1-SoEOK97Rf43acrmxEmKSZ9aWXmOHgG0MxgipkWkVfY/edit>

## Agenda

Extracted from **tsc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/node

* process: add allowedEnvironmentNodeFlags property [#19335](https://github.com/nodejs/node/pull/19335)
* Nominating bcoe as a collaborator [#20242](https://github.com/nodejs/node/issues/20242)

### nodejs/TSC

* Tracking issue for updating TSC on Board Meetings [#476](https://github.com/nodejs/TSC/issues/476)
* Strategic Initiatives - Tracking Issue [#423](https://github.com/nodejs/TSC/issues/423)
* Proposal: add all new core modules under a scope? (too late for http2) [#389](https://github.com/nodejs/TSC/issues/389)

### nodejs/admin

* Propose team discussion policy [#121](https://github.com/nodejs/admin/pull/121)

## Invited

* Anna Henningsen @addaleax (TSC)
* Сковорода Никита Андреевич @ChALkeR (TSC)
* Colin Ihrig @cjihrig (TSC)
* Daniel Bevenius @danbev (TSC)
* Franziska Hinkelmann @fhinkel (TSC)
* Gibson Fahnestock @gibfahn (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* James M Snell @jasnell (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Myles Borins @MylesBorins (TSC)
* Ali Ijaz Sheikh @ofrobots (TSC)
* Rod Vagg @rvagg (TSC)
* Michaël Zasso @targos (TSC)
* Sakthipriyan Vairamani @thefourtheye (TSC)
* Timothy Gu @TimothyGu (TSC)
* Rich Trott @Trott (TSC)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Zoom link: https://zoom.us/j/611357642
Regular password

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

Many of us will be on IRC in #node-dev on Freenode if you'd like to interact, we have a Q/A session scheduled at the end of the meeting if you'd like us to discuss anything in particular. @nodejs/collaborators in particular if there's anything you need from the TSC that's not worth putting on as a separate agenda item, this is a good place for that

**Comment by benjamingr** [comment] 2018-06-11 15:02
I don't think `process: add allowedEnvironmentNodeFlags property` needs TSC agenda anymore since the issue is that we weren't sure we need/want it and we were looking for collaborators to endorse it. I ran into a use case today that required it so I'm happy with it.

Of course, it would be _good_ if you discussed it - but you're always looking to make the agenda smaller before meetings so I figured it might help.

Let me know if you'd like me to weigh into "Propose team discussion policy #121" or to explain/elaborate on it.

**Comment by Trott** [comment] 2018-06-11 21:46
> I don't think `process: add allowedEnvironmentNodeFlags property` needs TSC agenda anymore since the issue is that we weren't sure we need/want it and we were looking for collaborators to endorse it. I ran into a use case today that required it so I'm happy with it.

I wish I could agree, but @vkurchatkin is -1 on it, so I don't think it can land without TSC approval.

@nodejs/tsc: I'd invite you to look closely at that issue as a vote seems likely. It would be great if we could have sufficient opinions form to be able to get a result on the vote one way or the other. The PR has been open for 3 months and I think the case has been made for both sides pretty thoroughly. 

For the record, I'm fine with "yes" or "no" on it, but I'm not fine with "kick it back to GitHub". We're asking a lot (even if it's mostly psychologically) of @boneskull to manage a PR for months without knowing if there's support for the feature or not.

Easy link: https://github.com/nodejs/node/pull/19335

**Comment by jasnell** [comment] 2018-06-13 12:13
I will be on a flight back to California this afternoon so will be missing the call.

I'm fine with `process.allowedNodeEnvironmentFlags` landing tho I'm not thrilled about adding to the `process` object.

**Comment by joyeecheung** [comment] 2018-06-13 12:29
I abstain. Not very happy about adding yet another property to `process`, but I do see to point of adding it.

**Comment by targos** [comment] 2018-06-13 12:33
I abstain too.

**Comment by danbev** [comment] 2018-06-13 12:51
I abstain.

**Comment by mcollina** [comment] 2018-06-13 13:13
I'm going to miss the call, it will be at midnight.

I'll also miss the next one because I'll be on vacation.

**Comment by mcollina** [comment] 2018-06-13 13:13
I'm going to miss the call, it will be at midnight.

I'll also miss the next one because I'll be on vacation.

**Comment by cjihrig** [comment] 2018-06-13 13:38
I abstain on the `process.allowedNodeEnvironmentFlags` issue. I'm not sure if I'll be able to make it to this one.

**Comment by mcollina** [comment] 2018-06-13 13:39
I'm in favor of `process.allowedNodeEnvironmentFlags`. I LGTM'd the PR.

**Comment by danbev** [comment] 2018-06-13 14:18
I'm going to have to  pass on the meeting tonight, just to late I'm afraid.

**Comment by fhinkel** [comment] 2018-06-13 14:51
I abstain on the process.allowedNodeEnvironmentFlags issue. I'm not sure if I'll be able to make it to this one.

**Comment by MylesBorins** [comment] 2018-06-13 15:23
I just added #20242 to the agenda

**Comment by benjamingr** [comment] 2018-06-13 15:30
@MylesBorins there is also the nomination in https://github.com/nodejs/node/issues/21285 (relatively new) and https://github.com/nodejs/node/issues/21096 - as both are uncontroversial (similarly to #20242) then maybe they should be added too?

cc @Trott @thefourtheye 

Note: I am not adding the tsc-agenda label to them or asking for the TSC to review them necessarily, mostly just want to figure out the process :)

**Comment by joyeecheung** [comment] 2018-06-14 06:00
Fell asleep and my alarm did not work for me, sorry

**Comment by Trott** [comment] 2018-06-14 16:06
Minutes PR from @mhdawson at https://github.com/nodejs/TSC/pull/552. Closing this issue...

**Closed by Trott** 2018-06-14 16:06 UTC

**Comment by Trott** [comment] 2018-06-14 16:33
Belated moderation report for this week: 

* One issue was locked.
* One spam comment was deleted from a YouTube chat.

@nodejs/tsc @nodejs/community-committee @nodejs/moderation More details available upon request. (Contact me in email, IRC DMs, or open an issue in the moderation repo.)
