### ISSUE TITLE
Nominating @BethGriggs to the TSC

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/TSC#718] opened 2019-06-17 19:44 UTC
No objections from the TSC so far and Beth has given a 👍 so I'm nominating her for the TSC. Beth has been shouldering a huge chunk of the LTS work for the last year and has begun being as focused on strategy and long term management of the program as getting the day to day work done. As I scale back my involvement in release I think it is a great idea to get someone else on the TSC who is helping to own that strategic initiative!

**Comment by mhdawson** [comment] 2019-06-17 19:46
+1

**Comment by mcollina** [comment] 2019-06-17 19:47
+1

Il giorno lun 17 giu 2019 alle 21:46 Michael Dawson <
notifications@github.com> ha scritto:

**Comment by sam-github** [comment] 2019-06-17 19:48
+1

**Comment by richardlau** [comment] 2019-06-17 20:49
This should be on the TSC agenda as [per the charter](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-4-establishment-of-the-tsc)?

> Changes to TSC membership should be posted in the agenda, and may be suggested as any other agenda item.

**Comment by mhdawson** [comment] 2019-06-17 20:52
I'll add to the agenda.

**Comment by Trott** [comment] 2019-06-17 21:12
> This should be on the TSC agenda as [per the charter](https://github.com/nodejs/TSC/blob/master/TSC-Charter.md#section-4-establishment-of-the-tsc)?
> 
> > Changes to TSC membership should be posted in the agenda, and may be suggested as any other agenda item.

It's only the changes to the membership that need to be posted in the agenda--in other words, when we finally vote on bringing her in (or not). That said, this is worth a mention in the Announcements section for sure.

**Comment by danbev** [comment] 2019-06-18 03:28
+1

**Comment by ChALkeR** [comment] 2019-06-18 08:04
+1

**Comment by fhinkel** [comment] 2019-06-18 10:40
+1

**Comment by joyeecheung** [comment] 2019-06-18 15:07
+1

**Comment by gabrielschulhof** [comment] 2019-06-19 16:24
+1

**Comment by cjihrig** [comment] 2019-06-19 17:21
+1

**Comment by mhdawson** [comment] 2019-07-08 15:30
Beth was invited to the last 3 TSC meetings and attended the 2/3 that were held. 

We have 14/18 +1's and no objections.

I suggest we confirm her membership in the meeting this week.

**Comment by mhdawson** [comment] 2019-07-10 18:31
There were no objections in the meeting and normally I think that would have let us confirm the nomination based on the votes in this issue and lack of objections in the meeting. @nodejs/tsc the wrinkle is that the Redhat Acquisition just closed.  Redhat will be managed as a separate company but my assumption is that we would still come under the same cap (let me know if you disagree). 
Based on that assumption IBM would already be at the cap of 4 based on the current TSC membership of 18 people.

My preference would have been if Bethany had been confirmed and we could have dealt with the cap later as we (IBM) would then look at how to adjust to the cap without it just affecting the last person to be added.

Since the nomination is a recognition of the work that Bethany has been putting into the project and the value of having her voice in TSC discussions I've been thinking about a few options.

My first one is some sort of rotation where we'd have one of the IBM members rotate out every 2 months and another one re-join.  Of course, this would be subject to our regular process which is to re-nominate/confirm the request of an Emeriti member to rejoin, just like we have for other Emeriti members in the past.

The other thing I've been thinking about is that it is useful for people like Sam to be able to report on where we are on the Security triage, or Bethany on Releases so I'm wondering if it would be ok for the person who has rotated off to continue to join the TSC members as an observer. Not sure if this crosses the line or not?

I'm just thinking of potential ideas to balance between concerns over membership from a single company and trying to maximize the effectiveness of our collaborators.  Please let me know if I'm completely off base or you feel that these suggestions go against the spirit of the limit on TSC members from a single company and I'll drop these kinds of suggestions.

**Comment by cjihrig** [comment] 2019-07-10 19:00
Another option would be for each company to have a single vote - although I think we would still want a hard upper limit on membership.

**Comment by MylesBorins** [comment] 2019-07-10 19:08
Considering the membership clause is in our charter I don't feel that we have much wiggle room without drafting changes (and getting those approved by CPC /w heads up to board). We have in the past required a company to have a member step down based on these rules so it does not seem fair to find ways to work around it.

I believe for board memebership rules subsidiaries, even if separately managed, still count towards the head count rules. For example we cannot have both community board seats be from the same company.

One solution would be to onboard another person first, bringing our count to 20 and making it so IBM would only be 24%

**Comment by mhdawson** [comment] 2019-07-10 19:50
@MylesBorins just so I understand do you see "rotating" as trying work around the limit?   I was not suggesting suggested that we'd have a member step down, only that we'd change who that was over time...

**Comment by mhdawson** [comment] 2019-07-10 20:50
@sam-github suggested I clarify more specifically as

The mechanism for rotation would that one person would step down, then later another person would step down, and a replacement would be nominated

**Comment by Trott** [comment] 2019-07-10 23:28
I think rotating is a perfectly acceptable, even laudable, solution to the problem.

That said, I think Myles's suggestion that we can nominate at least one more person is a good idea too, considering that we have (in my estimation) at least three other people who are obvious folks to consider for a nomination. I'll send email to TSC to discuss that more.

**Comment by Fishrock123** [comment] 2019-07-11 01:12
> Another option would be for each company to have a single vote - although I think we would still want a hard upper limit on membership.

I am very much not for this idea.

TSC seats are supposed to be individually held, and kept with individuals even when transferring companies, etc. They are supposed to represent as best as possible (and so, this rule) the individual contributor's judgement. Moving to per-company would be a huge step backwards and would possibly lead us to other less savoury rule changes in the future.

**Comment by cjihrig** [comment] 2019-07-11 01:15
I actually agree with @Fishrock123. I retract my previous comment 😄

**Comment by Fishrock123** [comment] 2019-07-11 01:20
I am also a bit hesitant on rotation, and I'd like to think about it a bit more.

I would rather not adjust our operations based on immediate circumstance when other options are available. _(Other options include someone from IBM not remaining a TSC member, unfortunately. 😞)_

**Comment by Fishrock123** [comment] 2019-07-24 20:21
Ok yeah, any 'official' rotation I think also eats into my previous point.

I think a longer term rotation by IBM itself (and so tsc members going fully on and off the tsc), could perhaps work.

**Comment by Fishrock123** [comment] 2019-09-11 16:44
+1

**Comment by mhdawson** [comment] 2019-09-11 18:14
We discussed in the TSC meeting today and agreed nomination can progress.

As per TSC charter we need a vote.  @nodejs/tsc, we'll consider +1s in this issue to be a yes vote unless an objection is raised in this issue before the end of this week.

The following people were in attendance in the meeting and are considered yes votes as well:
* Beth Griggs @BethGriggs (guest participant)
* James Snell @jasnell (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Gireesh Punathil @gireeshpunathil (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Tobias Nießen @tniessen (guest participant)
* Rich Trott @Trott (TSC)
* Sam Roberts @sam-github (TSC)

@nodejs/tsc, if you have not commented in this issue before or would like to change your vote please comment in the issue before the end of the week.  Michael will plan to tally votes and open PR's to add to TSC if appropriate on Monday next week

**Comment by targos** [comment] 2019-09-11 18:19
+1

**Comment by addaleax** [comment] 2019-09-11 21:33
+1

**Comment by cjihrig** [comment] 2019-09-12 01:13
+1

**Comment by apapirovski** [comment] 2019-09-12 01:23
+1

**Comment by danbev** [comment] 2019-09-12 03:50
+1

**Comment by MylesBorins** [comment] 2019-09-12 05:16
making +1 explicit

**Comment by mhdawson** [comment] 2019-09-13 13:09
We have 17/18 +1s and no objections so considering vote complete and acceptance onto the TSC complete.  Will PR addition.

**Comment by gireeshpunathil** [comment] 2019-09-13 13:18
converting my 👍 to an explicit +1!

**Comment by mhdawson** [comment] 2019-09-13 13:34
PR to add to mainling list: https://github.com/nodejs/email/pull/144

**Comment by mhdawson** [comment] 2019-09-13 13:38
PR to add to invitee list for TSC meetings: https://github.com/nodejs/create-node-meeting-artifacts/pull/76

**Comment by mhdawson** [comment] 2019-09-13 13:55
PR to add to TSC list in nodejs/node: https://github.com/nodejs/node/pull/29546

**Comment by mhdawson** [comment] 2019-09-13 14:04
checklist once PR in nodejs/node lands:

- [ ] Add the new member to the @nodejs/tsc and @nodejs/security-tsc teams.
- [ ] Change the new member's role in the GitHub nodejs organization to Owner.
- [ ] Add them to the @nodejs-private org and with an Owner role.
- [ ] Add them to the @nodejs-private/security-tsc team.

**Comment by mhdawson** [comment] 2019-09-13 15:01
Checklist complete. @BethGriggs welcome to the TSC!

**Closed** 2019-09-13 15:06 UTC
Labels: tsc-agenda
