### ISSUE TITLE
tsc command often griefs projects

### ISSUE THREAD

**Issue by SephReed** [nodejs/TSC#1296] opened 2022-10-21 19:03 UTC
Most people actively don't want a bunch of `.js` files spread throughout their project, put next to the `.ts` ones.  Unfortunately, this is the default behavior of `tsc`.

It may make sense to warn users before generating tons of files in this way.  Something like:
```
you don't have a dist target, so the following files will be created:
/me/code/project/src/user/user.js
/me/code/project/src/user/user-type.js
/me/code/project/src/user/user-connect.js
/me/code/project/src/home/home.js
/me/code/project/src/home/home-list.js
/me/code/project/src/home/home-buyer.js
/me/code/project/src/paint/red.js
/me/code/project/src/paint/orange.js
/me/code/project/src/paint/yellow.js
/me/code/project/src/paint/green.js
/me/code/project/src/paint/blue.js
/me/code/project/src/paint/magenta.js
/me/code/project/src/number/one.js
/me/code/project/src/number/two.js
/me/code/project/src/number/three.js
/me/code/project/src/number/four.js
/me/code/project/src/number/five.js
/me/code/project/src/number/six.js
/me/code/project/src/number/seven.js
/me/code/project/src/number/eight.js
/me/code/project/src/number/nine.js
/me/code/project/src/number/ten.js

would you like to continue? (y/n):
```

If changing default behavior is unacceptable, perhaps adding something like `tsc --safe` that actively attempts to respect project cleanliness.  The question of cleanliness being: how hard is it to undo this?

**Comment by cjihrig** [comment] 2022-10-21 19:09
Closing as a duplicate of https://github.com/nodejs/TSC/issues/1296

**Closed by cjihrig** 2022-10-21 19:09 UTC
