### ISSUE TITLE
Node.js Foundation Technical Steering Committee (TSC) Meeting 2019-05-22

### ISSUE THREAD

**Issue by mhdawson** [nodejs/TSC#709] opened 2019-05-20 12:05 UTC
## Time

**UTC Wed 22-May-2019 12:00 (12:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 22-May-2019 05:00 (05:00 AM) |
| US / Mountain | Wed 22-May-2019 06:00 (06:00 AM) |
| US / Central  | Wed 22-May-2019 07:00 (07:00 AM) |
| US / Eastern  | Wed 22-May-2019 08:00 (08:00 AM) |
| London        | Wed 22-May-2019 13:00 (01:00 PM) |
| Amsterdam     | Wed 22-May-2019 14:00 (02:00 PM) |
| Moscow        | Wed 22-May-2019 15:00 (03:00 PM) |
| Chennai       | Wed 22-May-2019 17:30 (05:30 PM) |
| Hangzhou      | Wed 22-May-2019 20:00 (08:00 PM) |
| Tokyo         | Wed 22-May-2019 21:00 (09:00 PM) |
| Sydney        | Wed 22-May-2019 22:00 (10:00 PM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Technical%20Steering%20Committee%20(TSC)+Meeting+2019-05-22&iso=20190522T12
* or http://www.wolframalpha.com/input/?i=12PM+UTC%2C+May+22%2C+2019+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1Vti8zHfMR8bz2CoS-cLmMW_f_DbgFSBirQa7w12HuUA/edit>

## Agenda

Extracted from **tsc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/node

* benchmark: refactor buffer benchmarks [#26418](https://github.com/nodejs/node/pull/26418)

### nodejs/TSC

* Reevaluate meeting times [#707](https://github.com/nodejs/TSC/issues/707)
* doc: update TSC charter [#698](https://github.com/nodejs/TSC/pull/698)
* Tracking issue for updating TSC on Board Meetings [#476](https://github.com/nodejs/TSC/issues/476)
* Strategic Initiatives - Tracking Issue [#423](https://github.com/nodejs/TSC/issues/423)

## Invited

* Anna Henningsen @addaleax (TSC)
* Anatoli Papirovski @apapirovski (TSC)
* Сковорода Никита Андреевич @ChALkeR (TSC)
* Colin Ihrig @cjihrig (TSC)
* Daniel Bevenius @danbev (TSC)
* Franziska Hinkelmann @fhinkel (TSC)
* Jeremiah Senkpiel @Fishrock123 (TSC)
* Gabriel Schulhof @gabrielschulhof (TSC)
* Gireesh Punathil @gireeshpunathil (TSC)
* James Snell @jasnell (TSC)
* Joyee Cheung @joyeecheung (TSC)
* Matteo Collina @mcollina (TSC)
* Michael Dawson @mhdawson (TSC)
* Myles Borins @MylesBorins (TSC)
* Sam Roberts @sam-github (TSC)
* Michaël Zasso @targos (TSC)
* Sakthipriyan Vairamani @thefourtheye (TSC)
* Rich Trott @Trott (TSC)

## Notes

The agenda comes from issues labelled with `tsc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Zoom link: https://zoom.us/j/611357642
Regular password

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

Many of us will be on IRC in #node-dev on Freenode if you'd like to interact, we have a Q/A session scheduled at the end of the meeting if you'd like us to discuss anything in particular. @nodejs/collaborators in particular if there's anything you need from the TSC that's not worth putting on as a separate agenda item, this is a good place for that.

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by mcollina** [comment] 2019-05-20 15:43
I won't be able to join.

**Comment by Trott** [comment] 2019-05-20 18:14
In https://github.com/nodejs/node/pull/26418, a vote started to happen, but @sam-github suggested that a vote was premature. But no one responded discussion-wise, including @mscdex (opposes the PR), @BridgeAR (authored the PR), or anyone else.

I propose we continue with the vote, but there are other reasonable approaches to take.

**Comment by danbev** [comment] 2019-05-21 16:48
There are only 3 people who have said yes (including me) and one maybe. I'm not sure what the "cut off" has been before but should we consider cancelling?

**Comment by mcollina** [comment] 2019-05-21 17:07
+1 to cancel

**Comment by cjihrig** [comment] 2019-05-21 17:11
+1 to cancelling

**Comment by MylesBorins** [comment] 2019-05-22 03:03
+1 to cancel

**Comment by danbev** [comment] 2019-05-22 07:20
There have been no objections so I'll go ahead and cancel todays meeting. 

Is there anything else besides closing this PR that I need to do when cancelling a meeting?

**Closed by danbev** 2019-05-22 07:20 UTC

**Comment by Trott** [comment] 2019-05-23 20:47
> Is there anything else besides closing this PR that I need to do when cancelling a meeting?

No. Usually, the issue is closed when a PR for minutes is opened, but that doesn't happen for a canceled meeting, obviously.

(Optional, but I'm going to mention @nodejs/moderation here as we usually get a comment to update us on their activity.)
