### ISSUE TITLE
Timing of TSC member addition / resignation

### ISSUE THREAD

**Issue by tniessen** [nodejs/TSC#817] opened 2020-02-12 20:28 UTC
If @BridgeAR isn't added to the TSC (#811) before @Fishrock123 leaves the TSC (https://github.com/nodejs/node/pull/31725), and if I am not mistaken about the number of IBM employees on the TSC, this clause will come into effect:

> If removal or resignation of a TSC member, or a change of employment by a TSC member, creates a situation where more than one-fourth of the TSC membership shares an employer, then the situation must be immediately remedied by the resignation or removal of one or more TSC members affiliated with the over-represented employer(s).

It might be too early to add @BridgeAR, given that he hasn't had a chance to attend any meetings yet. We can avoid this clause from coming into effect if @Fishrock123 is okay with delaying his resignation for a while, but I understand if he is not, and we should in no way prevent him from stepping down.

cc @nodejs/tsc

**Comment by mhdawson** [comment] 2020-02-12 20:32
@tniessen thanks for opening, just catching up on latest events.

@Fishrock123 just let me know what your feeling is on this.  If you don't want to delay I'll get started on figuring out who drops out on the IBM side.

**Comment by Fishrock123** [comment] 2020-02-12 21:29
I think that is rather a question for the TSC.

Sure, I could still vote on anything important if it was sent to me directly, but I am not involved by any real meaningful sense of the term, and am also likely to forget about the regular meetings.

Does asking me to stay on then reflect poorly on the integrity of the TSC? I don't know, we are basically asking philosophical questions.

If it makes it easier I can stay for a few more weeks but don't expect me to... well, be particularly involved.

**Comment by mhdawson** [comment] 2020-02-12 21:46
@nodejs/tsc please chime in on what you think is best.

**Comment by cjihrig** [comment] 2020-02-12 22:05
> Does asking me to stay on then reflect poorly on the integrity of the TSC?

I think so. If any collaborator were to merge https://github.com/nodejs/node/pull/31725, would that mean @Fishrock123 is officially off of the TSC at that moment? That seems kind of silly. What if someone else on the TSC also resigned (for legitimate reasons, or just to watch the TSC squirm)?

**Comment by jasnell** [comment] 2020-02-12 22:16
If @BridgeAR's nomination (or any new nomination) wasn't already in progress I would say that the rule would apply. But since there is an active nomination in the works and it's not likely to take too long, we can likely assume a safe grace period for the IBMers. Alternatively, one of the IBMers could temporarily and voluntarily move to emeritus status while the nomination is still open. I highly doubt anyone would object to them coming back off emeritus once @BridgeAR's nomination is finalized.

**Comment by sam-github** [comment] 2020-02-12 22:29
I wouldn't want it to look like IBM isn't following the membership rules. I'll resign from the TSC if membership ends up over quota.

**Comment by mhdawson** [comment] 2020-02-12 22:33
@sam-github thanks for jumping in with the offer.

**Comment by jasnell** [comment] 2020-02-12 22:34
@sam-github ... I don't think a full resignation is required. Moving temporarily to emeritus should work also.

**Comment by sam-github** [comment] 2020-02-13 00:29
Ok, will do when I need to. I think that is after https://github.com/nodejs/node/pull/31725 lands, but someone tell me if its needed earlier.

**Comment by Fishrock123** [comment] 2020-02-13 00:49
After, yes. I'll land that soon.

**Comment by gireeshpunathil** [comment] 2020-02-13 16:32
I had word with @sam-github . I will go emeritus to address the situation. The WIP PR is in, just waiting for https://github.com/nodejs/node/pull/31725 to be landed.

**Comment by mcollina** [comment] 2020-02-13 16:39
In case, I would like nominate @gireeshpunathil _immediately_ to the TSC to join together with @BridgeAR. It's a little bit of a dance but within the rules.

**Comment by mhdawson** [comment] 2020-02-14 21:56
@gireeshpunathil thanks for doing that.

**Comment by mhdawson** [comment] 2020-02-21 22:49
I think this can be close, let me know if closing was not the right thing to do.  @mcollina maybe you could open an issue with your nomination to bring @gireeshpunathil back on the CPC when @BridgeAR is confirmed. I think it would be good to capture that in it's own issue along with the +1s

**Closed** 2020-02-23 14:56 UTC
