### ISSUE TITLE
Nominating Shelley Vohr (codebytere) to the TSC

### ISSUE THREAD

**Issue by Trott** [nodejs/TSC#832] opened 2020-03-03 06:25 UTC
I would like to nominate @codebytere to the TSC. In addition to [her excellent code contributions to Node.js core](https://github.com/nodejs/node/commits?author=codebytere), Shelley is the only active releaser not yet on the TSC.  She would also bring representation of significant entities to the TSC, specifically Electron, embedders in general, and Microsoft. Shelley is also a current member of the Moderation Team.

There have been no objections from the private TSC discussion, and I have contacted Shelley privately to verify their interest.

**Comment by MylesBorins** [comment] 2020-03-03 06:27
+1 🎉🎉🎉🎉

**Comment by gabrielschulhof** [comment] 2020-03-03 06:45
Absolutely! +1

**Comment by danbev** [comment] 2020-03-03 08:22
+1

**Comment by mcollina** [comment] 2020-03-03 08:41
+1

**Comment by cjihrig** [comment] 2020-03-03 15:05
+1

**Comment by jasnell** [comment] 2020-03-03 20:08
+1

**Comment by mhdawson** [comment] 2020-03-03 23:22
+1

**Comment by tniessen** [comment] 2020-03-04 00:48
+1

**Comment by targos** [comment] 2020-03-04 06:43
+1!

**Comment by codebytere** [comment] 2020-03-05 02:01
Extremely excited and honored, thank you all for this nomination 🙇‍♀

**Comment by fhinkel** [comment] 2020-03-06 10:50
+1

**Comment by ChALkeR** [comment] 2020-03-07 02:41
+1!

**Comment by joyeecheung** [comment] 2020-03-07 16:12
+1

**Comment by apapirovski** [comment] 2020-03-11 15:03
+1  🎉

**Comment by addaleax** [comment] 2020-03-20 09:59
+1

**Comment by mhdawson** [comment] 2020-03-24 21:46
By my count we have >1/2 TSC as +1s and no objections. Considering approved will start on onboarding checklist.


- [ ] Confirm that the new member has read, understands, and agrees to uphold the
  [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md).
  @codebytere can you comment in this issue confirming this.

- [ ] Add the new member to the `@nodejs/tsc` and `@nodejs/security-tsc` teams.
- [ ] Change the new member's role in the GitHub `nodejs` organization to `Owner`.
- [ ] Add them to the `@nodejs-private` org and with an `Owner` role.
- [ ] Add them to the `@nodejs-private/security-tsc` team.
- [ ] Invite them to the HackerOne [Node.js team](https://hackerone.com/nodejs/team_members).
- [ ] Add them to the `tsc` and `crypto-export` mailing lists.
- [ ] Update the `@nodejs/node` repository README to reflect membership in the TSC.
- [ ] Update https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/invited_tsc and https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/observers_tsc to reflect membership in the TSC.

**Comment by codebytere** [comment] 2020-03-24 21:48
@mhdawson Confirmed, I have read, understood, and am committed to upholding the CoC. I think we can also check off

> Change the new member's role in the GitHub nodejs organization to Owner.

since i already have that role a a function of my Moderation team membership :)

**Comment by mhdawson** [comment] 2020-03-24 21:58
@codebytere thanks!

**Comment by mhdawson** [comment] 2020-03-24 22:16
PR to add to meeting issue generator: https://github.com/nodejs/create-node-meeting-artifacts/pull/89

**Comment by mhdawson** [comment] 2020-03-25 20:45
Checklist complete, closing.

**Closed by mhdawson** 2020-03-25 20:45 UTC
